CONTACT_DATABASE_PATH=/var/lib/vibmail-public-contact/contact.sqlite3
CONTACT_HASH_SECRET={{CONTACT_HASH_SECRET}}
CONTACT_ADMIN_RECIPIENT={{ADMIN_EMAIL}}
CONTACT_FROM_ADDRESS="MailStack Website <website@{{MAIL_DOMAIN}}>"
CONTACT_PUBLIC_ORIGIN=https://{{PUBLIC_HOSTNAME}}
CONTACT_SENDMAIL_PATH=/usr/sbin/sendmail
CONTACT_LOG_LEVEL=INFO
