# Generated by Django 5.2.14 on 2026-06-27 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_existing_user_policies(apps, _schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split(".", 1)
    User = apps.get_model(app_label, model_name)
    UserAccessPolicy = apps.get_model("accounts", "UserAccessPolicy")
    UserAccessPolicy.objects.bulk_create(
        [UserAccessPolicy(user_id=user_id) for user_id in User.objects.values_list("id", flat=True)],
        ignore_conflicts=True,
    )


def remove_existing_user_policies(apps, _schema_editor):
    UserAccessPolicy = apps.get_model("accounts", "UserAccessPolicy")
    UserAccessPolicy.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_delete_messages', models.BooleanField(default=False)),
                ('can_delete_mailboxes', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vibmail_access_policy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_existing_user_policies, reverse_code=remove_existing_user_policies),
    ]
