# Generated by Django 5.2.14 on 2026-06-26 18:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=80, unique=True)),
                ('status', models.CharField(default='unknown', max_length=32)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
