# Generated by Django 5.2.14 on 2026-06-26 18:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailboxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_file_key', models.CharField(max_length=1024)),
                ('source_sha256', models.CharField(max_length=64)),
                ('message_id_header', models.CharField(blank=True, max_length=998)),
                ('sender_name', models.CharField(blank=True, max_length=500)),
                ('sender_address', models.CharField(blank=True, db_index=True, max_length=320)),
                ('recipient_addresses', models.JSONField(blank=True, default=list)),
                ('cc_addresses', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(blank=True, db_index=True, max_length=998)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('parsed_at', models.DateTimeField()),
                ('text_body', models.TextField(blank=True)),
                ('sanitized_html_body', models.TextField(blank=True)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('has_attachments', models.BooleanField(default=False)),
                ('parse_status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Warning'), ('error', 'Error'), ('oversized', 'Oversized')], db_index=True, default='ok', max_length=16)),
                ('parse_warning', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mailboxes.mailbox')),
            ],
            options={
                'ordering': ['-received_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('original_filename', models.CharField(blank=True, max_length=1000)),
                ('safe_filename', models.CharField(max_length=255)),
                ('stored_filename', models.CharField(max_length=255, unique=True)),
                ('declared_mime_type', models.CharField(blank=True, max_length=255)),
                ('detected_mime_type', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('storage_relative_path', models.CharField(max_length=500)),
                ('is_inline', models.BooleanField(default=False)),
                ('content_id', models.CharField(blank=True, max_length=998)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='vib_messages.message')),
            ],
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['mailbox', '-received_at'], name='vib_message_mailbox_4e3a62_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['mailbox', 'is_read'], name='vib_message_mailbox_00cc04_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['parse_status'], name='vib_message_parse_s_aeacc8_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('mailbox', 'source_file_key'), name='message_source_per_mailbox_unique'),
        ),
    ]
