# Generated by Django 5.2.14 on 2026-06-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxes', '0002_postfix_virtual_mailboxes_view'),
        ('vib_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='storage_relative_path',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['mailbox', 'has_attachments'], name='vib_message_mailbox_e4ba48_idx'),
        ),
    ]
