# Generated by Django 5.2.14 on 2026-06-27 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxes', '0003_mailboxmembership_and_more'),
        ('vib_messages', '0002_alter_attachment_storage_relative_path_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['mailbox', 'deleted_at', 'is_read'], name='vib_message_mailbox_8ed622_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['deleted_at', 'id'], name='vib_message_deleted_b204cd_idx'),
        ),
    ]
