# Generated by Django 5.2.14 on 2026-06-27 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

POSTGRES_SQL = """
CREATE VIEW postfix_virtual_mailboxes AS
SELECT lower(email_address) AS email,
       maildir_relative_path AS maildir_path
FROM mailboxes_mailbox
WHERE status = 'active'
  AND deleted_at IS NULL
  AND local_part = lower(local_part)
  AND length(local_part) BETWEEN 1 AND 64
  AND lower(email_address) = local_part || '@vibmail.my'
  AND maildir_relative_path = 'vibmail.my/' || local_part || '/Maildir/'
  AND local_part ~ '^[a-z0-9](?:[a-z0-9._-]{0,62}[a-z0-9])?$'
  AND position('..' in local_part) = 0
"""

SQLITE_SQL = """
CREATE VIEW postfix_virtual_mailboxes AS
SELECT lower(email_address) AS email,
       maildir_relative_path AS maildir_path
FROM mailboxes_mailbox
WHERE status = 'active'
  AND deleted_at IS NULL
  AND local_part = lower(local_part)
  AND length(local_part) BETWEEN 1 AND 64
  AND lower(email_address) = local_part || '@vibmail.my'
  AND maildir_relative_path = 'vibmail.my/' || local_part || '/Maildir/'
  AND local_part NOT GLOB '*[^a-z0-9._-]*'
  AND substr(local_part, 1, 1) GLOB '[a-z0-9]'
  AND substr(local_part, -1, 1) GLOB '[a-z0-9]'
  AND instr(local_part, '..') = 0
"""

def drop_postfix_view(_apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        schema_editor.execute("DROP VIEW IF EXISTS postfix_virtual_mailboxes")

def recreate_postfix_view(_apps, schema_editor):
    if schema_editor.connection.vendor == "mysql":
        return
    schema_editor.execute("DROP VIEW IF EXISTS postfix_virtual_mailboxes")
    sql = POSTGRES_SQL if schema_editor.connection.vendor == "postgresql" else SQLITE_SQL
    schema_editor.execute(sql)



class Migration(migrations.Migration):

    dependencies = [
        ('mailboxes', '0002_postfix_virtual_mailboxes_view'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(drop_postfix_view, reverse_code=recreate_postfix_view),
        migrations.CreateModel(
            name='MailboxMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='mailbox',
            name='mailbox_valid_status',
        ),
        migrations.AddField(
            model_name='mailbox',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_mailboxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=16),
        ),
        migrations.AddIndex(
            model_name='mailbox',
            index=models.Index(fields=['deleted_at', 'status'], name='mailboxes_m_deleted_8a0c49_idx'),
        ),
        migrations.AddConstraint(
            model_name='mailbox',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'disabled', 'deleted'])), name='mailbox_valid_status'),
        ),
        migrations.AddField(
            model_name='mailboxmembership',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailbox_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailboxmembership',
            name='mailbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='mailboxes.mailbox'),
        ),
        migrations.AddField(
            model_name='mailboxmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mailboxmembership',
            index=models.Index(fields=['user', 'mailbox'], name='mailboxes_m_user_id_e09871_idx'),
        ),
        migrations.AddIndex(
            model_name='mailboxmembership',
            index=models.Index(fields=['mailbox', 'user'], name='mailboxes_m_mailbox_9a42b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='mailboxmembership',
            constraint=models.UniqueConstraint(fields=('user', 'mailbox'), name='mailbox_membership_unique'),
        ),
        migrations.RunPython(recreate_postfix_view, reverse_code=drop_postfix_view),
    ]
